# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web_1" do |web1|
  	web1.vm.box = "ubuntu/xenial64"
  	web1.vm.synced_folder "www_1", "/var/www/html/"
  	web1.vm.network "forwarded_port", guest: 80, host: 8080
  	web1.vm.provision "shell", path: "script.sh"
	web1.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--name', 'web_1' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '1' ]
        	vb.customize [ 'modifyvm', :id, '--memory', '720' ]
        	vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', '70' ] 
     end
  end

  config.vm.define "web_2" do |web2|
  	web2.vm.box = "ubuntu/xenial64"
  	web2.vm.synced_folder "www_2", "/var/www/html/"
  	web2.vm.network "forwarded_port", guest: 80, host: 8008
  	web2.vm.provision "shell", path: "script.sh"
	web2.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--name', 'web_2' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '1' ]
        	vb.customize [ 'modifyvm', :id, '--memory', '720' ]
        	vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', '70' ]
      end
  end
end

